name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Convert repository name to lower case
      run: echo IMAGE_REPOSITORY="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: ${{ env.IMAGE_REPOSITORY }}/arma3server
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_with_ref: true
        push: true
